# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jif_gui/main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


import resource_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainGUI(object):
    def setupUi(self, MainGUI):
        MainGUI.setObjectName("MainGUI")
        MainGUI.setEnabled(True)
        MainGUI.resize(733, 619)
        self.centralwidget = QtWidgets.QWidget(MainGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(65, 140, 111, 25))
        self.pushButton.setObjectName("pushButton")
        self.tw_output = QtWidgets.QTableWidget(self.centralwidget)
        self.tw_output.setGeometry(QtCore.QRect(10, 380, 711, 161))
        self.tw_output.setObjectName("tw_output")
        self.tw_output.setColumnCount(8)
        self.tw_output.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tw_output.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_output.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_output.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_output.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_output.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_output.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_output.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_output.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_output.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_output.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_output.setItem(0, 1, item)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(180, 110, 361, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(180, 140, 361, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.b_search = QtWidgets.QPushButton(self.centralwidget)
        self.b_search.setGeometry(QtCore.QRect(150, 350, 411, 21))
        self.b_search.setObjectName("b_search")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(330, 90, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.cb_converter = QtWidgets.QComboBox(self.centralwidget)
        self.cb_converter.setGeometry(QtCore.QRect(65, 110, 111, 25))
        self.cb_converter.setObjectName("cb_converter")
        self.cb_converter.addItem("")
        self.cb_converter.addItem("")
        self.cb_converter.addItem("")
        self.cb_fpga = QtWidgets.QComboBox(self.centralwidget)
        self.cb_fpga.setGeometry(QtCore.QRect(550, 110, 111, 25))
        self.cb_fpga.setObjectName("cb_fpga")
        self.cb_fpga.addItem("")
        self.cb_fpga.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 140, 111, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.cb_clock = QtWidgets.QComboBox(self.centralwidget)
        self.cb_clock.setGeometry(QtCore.QRect(300, 170, 111, 25))
        self.cb_clock.setObjectName("cb_clock")
        self.cb_clock.addItem("")
        self.cb_clock.addItem("")
        self.cb_clock.addItem("")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 200, 111, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(650, 0, 81, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/adi_logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 733, 22))
        self.menubar.setObjectName("menubar")
        MainGUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainGUI)
        self.statusbar.setObjectName("statusbar")
        MainGUI.setStatusBar(self.statusbar)

        self.retranslateUi(MainGUI)
        QtCore.QMetaObject.connectSlotsByName(MainGUI)

    def retranslateUi(self, MainGUI):
        _translate = QtCore.QCoreApplication.translate
        MainGUI.setWindowTitle(_translate("MainGUI", "ADI JESD Configurator"))
        self.pushButton.setText(_translate("MainGUI", "Configure"))
        item = self.tw_output.verticalHeaderItem(0)
        item.setText(_translate("MainGUI", "1"))
        item = self.tw_output.horizontalHeaderItem(0)
        item.setText(_translate("MainGUI", "Lane Rate"))
        item = self.tw_output.horizontalHeaderItem(1)
        item.setText(_translate("MainGUI", "VCXO"))
        item = self.tw_output.horizontalHeaderItem(2)
        item.setText(_translate("MainGUI", "Converter Clock Rate"))
        item = self.tw_output.horizontalHeaderItem(3)
        item.setText(_translate("MainGUI", "Converter Sysref Rate"))
        item = self.tw_output.horizontalHeaderItem(4)
        item.setText(_translate("MainGUI", "FPGA Reference Rate"))
        item = self.tw_output.horizontalHeaderItem(5)
        item.setText(_translate("MainGUI", "FPGA Sysref Rate"))
        item = self.tw_output.horizontalHeaderItem(6)
        item.setText(_translate("MainGUI", "FPGA Config"))
        item = self.tw_output.horizontalHeaderItem(7)
        item.setText(_translate("MainGUI", "Clock Config"))
        __sortingEnabled = self.tw_output.isSortingEnabled()
        self.tw_output.setSortingEnabled(False)
        item = self.tw_output.item(0, 0)
        item.setText(_translate("MainGUI", "10000000000"))
        item = self.tw_output.item(0, 1)
        item.setText(_translate("MainGUI", "125000000"))
        self.tw_output.setSortingEnabled(__sortingEnabled)
        self.b_search.setText(_translate("MainGUI", "Search"))
        self.cb_converter.setItemText(0, _translate("MainGUI", "AD9680"))
        self.cb_converter.setItemText(1, _translate("MainGUI", "AD9144"))
        self.cb_converter.setItemText(2, _translate("MainGUI", "ADRV9009"))
        self.cb_fpga.setItemText(0, _translate("MainGUI", "Xilinx"))
        self.cb_fpga.setItemText(1, _translate("MainGUI", "Intel"))
        self.pushButton_2.setText(_translate("MainGUI", "Configure"))
        self.cb_clock.setItemText(0, _translate("MainGUI", "AD9523-1"))
        self.cb_clock.setItemText(1, _translate("MainGUI", "AD9528"))
        self.cb_clock.setItemText(2, _translate("MainGUI", "HMC7044"))
        self.pushButton_4.setText(_translate("MainGUI", "Configure"))
