name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: x64
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.23.0'
    - run: |
        cd adijif/d2
        chmod +x build.sh
        ./build.sh
        cd ../..
    - run: pip install "nox[uv]==2025.2.9"
    - run: pip install poetry==1.2.2
    - run: nox --sessions tests-3.8 coverage
    - name: Upload coverage reports
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        token: ${{secrets.CODECOV_TOKEN}}
