name: Build and Deploy Doc
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: pip install ".[cplex]"
    - run: pip install -r requirements_dev.txt
    - run: pip install -r doc/requirements.txt
    - run: |
        cd doc
        make html SPHINXOPTS="-W -v"
        cd ..
    - run: |
        cd doc
        make linkcheck

  deploy_dev:
    name: Deploy master docs
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Build and push doc
        run: |
         pip install ".[cplex]"
         pip install -r requirements_dev.txt
         pip install -r doc/requirements.txt
         cd doc
         export ADOC_TARGET_DEPTH=1
         make html
         cd ..

      - name: Publish doc
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/build/html
          destination_dir: main

  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Build Doc
        run: |
         pip install ".[cplex]"
         pip install -r requirements_dev.txt
         pip install -r doc/requirements.txt
         cd doc
         export ADOC_TARGET_DEPTH=1
         make html
         cd ..

      - name: Publish doc
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/build/html
