name: Build and Deploy Doc
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: pip install ".[cplex]"
    - run: pip install -r requirements_dev.txt
    - run: pip install $(tail --lines=+2 doc/requirements.txt)
    - run: |
        cd doc
        make html SPHINXOPTS="-W -v"
        cd ..
    - run: |
        cd doc
        make linkcheck

    - name: Store the generated doc
      uses: actions/upload-artifact@v4
      with:
        name: python${{ matrix.python-version }}_html
        path: doc/build/html

  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    if: >
      github.ref == 'refs/heads/main' ||
      github.event_name == 'pull_request' ||
      github.ref_type == 'tag'

    steps:
    - uses: analogdevicesinc/doctools/gh-pages-deploy@action
      with:
        new_tag: ${{ github.ref_type == 'tag' }}
        tag: ${{ github.ref_name }}
        name: python3.9_html

