# Runs tests via nox
# Runs on pull requests to main
name: Test on pull request
on:
  pull_request:
    branches: [main, master]
jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-22.04]
        python-version: ["3.9"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'
      - run: |
          cd adijif/d2
          chmod +x build.sh
          ./build.sh
          cd ../..
      - run: curl -fsSL https://d2lang.com/install.sh | sh -s --
      - run: pip install "nox[uv]==2025.2.9"
      - run: nox -p ${{ matrix.python-version }}

