name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: curl -fsSL https://d2lang.com/install.sh | sh -s --
    - run: pip install nox==2022.8.7
    - run: nox -p ${{ matrix.python-version }}
